### ISSUE TITLE
fontStyle normal doesn't exist

### ISSUE THREAD

**Issue by kurtextrem** [m-thorsen/vscode-material-mt#1]
This line: https://github.com/m-thorsen/vscode-material-mt/blob/17a8ec6a15795a4bd5fb1052e15d323abc6fb9f5/themes/common.json#L246 is faulty. There is no such value "normal". If you want to reset inherited styles, use `""`.

Anyway, great ideas to improve the Material Theme!

**Comment by m-thorsen** [comment]
I do see a few warnings in the token color section, I'll go through it and clean it up. 

Doesn't appear to break anything, though.

**Comment by m-thorsen** [comment]
Fixed in 0.2.5
