### ISSUE TITLE
No highlight color on quick action tooltips

### ISSUE THREAD

**Issue by glc-mvion** [m-thorsen/vscode-material-mt#6]
With the Materia variant, the quick action tooltip does not have a color for the selected item.

![image](https://user-images.githubusercontent.com/6715182/47283750-dd7cbf00-d5e4-11e8-908d-e3a2eb1c8144.png)

If you want, I can do the fix :smiley:

**Comment by m-thorsen** [comment]
Sure, give me a PR or describe the fix if you can.

**Comment by m-thorsen** [comment]
Merged!
